# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Boss/Desktop/LdP2/FINAL/KanaCrush-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Boss/Desktop/LdP2/FINAL/KanaCrush-main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Boss/Desktop/LdP2/FINAL/KanaCrush-main/CMakeFiles /mnt/c/Users/Boss/Desktop/LdP2/FINAL/KanaCrush-main/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Boss/Desktop/LdP2/FINAL/KanaCrush-main/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named KanaCrush

# Build rule for target.
KanaCrush: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KanaCrush
.PHONY : KanaCrush

# fast build rule for target.
KanaCrush/fast:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/build
.PHONY : KanaCrush/fast

src/1model/Menu.o: src/1model/Menu.cpp.o

.PHONY : src/1model/Menu.o

# target to build an object file
src/1model/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/Menu.cpp.o
.PHONY : src/1model/Menu.cpp.o

src/1model/Menu.i: src/1model/Menu.cpp.i

.PHONY : src/1model/Menu.i

# target to preprocess a source file
src/1model/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/Menu.cpp.i
.PHONY : src/1model/Menu.cpp.i

src/1model/Menu.s: src/1model/Menu.cpp.s

.PHONY : src/1model/Menu.s

# target to generate assembly for a file
src/1model/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/Menu.cpp.s
.PHONY : src/1model/Menu.cpp.s

src/1model/Welcome.o: src/1model/Welcome.cpp.o

.PHONY : src/1model/Welcome.o

# target to build an object file
src/1model/Welcome.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/Welcome.cpp.o
.PHONY : src/1model/Welcome.cpp.o

src/1model/Welcome.i: src/1model/Welcome.cpp.i

.PHONY : src/1model/Welcome.i

# target to preprocess a source file
src/1model/Welcome.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/Welcome.cpp.i
.PHONY : src/1model/Welcome.cpp.i

src/1model/Welcome.s: src/1model/Welcome.cpp.s

.PHONY : src/1model/Welcome.s

# target to generate assembly for a file
src/1model/Welcome.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/Welcome.cpp.s
.PHONY : src/1model/Welcome.cpp.s

src/1model/game/board/Mboard.o: src/1model/game/board/Mboard.cpp.o

.PHONY : src/1model/game/board/Mboard.o

# target to build an object file
src/1model/game/board/Mboard.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/game/board/Mboard.cpp.o
.PHONY : src/1model/game/board/Mboard.cpp.o

src/1model/game/board/Mboard.i: src/1model/game/board/Mboard.cpp.i

.PHONY : src/1model/game/board/Mboard.i

# target to preprocess a source file
src/1model/game/board/Mboard.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/game/board/Mboard.cpp.i
.PHONY : src/1model/game/board/Mboard.cpp.i

src/1model/game/board/Mboard.s: src/1model/game/board/Mboard.cpp.s

.PHONY : src/1model/game/board/Mboard.s

# target to generate assembly for a file
src/1model/game/board/Mboard.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/game/board/Mboard.cpp.s
.PHONY : src/1model/game/board/Mboard.cpp.s

src/1model/game/board/cell/Mcell.o: src/1model/game/board/cell/Mcell.cpp.o

.PHONY : src/1model/game/board/cell/Mcell.o

# target to build an object file
src/1model/game/board/cell/Mcell.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/game/board/cell/Mcell.cpp.o
.PHONY : src/1model/game/board/cell/Mcell.cpp.o

src/1model/game/board/cell/Mcell.i: src/1model/game/board/cell/Mcell.cpp.i

.PHONY : src/1model/game/board/cell/Mcell.i

# target to preprocess a source file
src/1model/game/board/cell/Mcell.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/game/board/cell/Mcell.cpp.i
.PHONY : src/1model/game/board/cell/Mcell.cpp.i

src/1model/game/board/cell/Mcell.s: src/1model/game/board/cell/Mcell.cpp.s

.PHONY : src/1model/game/board/cell/Mcell.s

# target to generate assembly for a file
src/1model/game/board/cell/Mcell.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/game/board/cell/Mcell.cpp.s
.PHONY : src/1model/game/board/cell/Mcell.cpp.s

src/1model/game/board/linked_list/Linked_list.o: src/1model/game/board/linked_list/Linked_list.cpp.o

.PHONY : src/1model/game/board/linked_list/Linked_list.o

# target to build an object file
src/1model/game/board/linked_list/Linked_list.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/game/board/linked_list/Linked_list.cpp.o
.PHONY : src/1model/game/board/linked_list/Linked_list.cpp.o

src/1model/game/board/linked_list/Linked_list.i: src/1model/game/board/linked_list/Linked_list.cpp.i

.PHONY : src/1model/game/board/linked_list/Linked_list.i

# target to preprocess a source file
src/1model/game/board/linked_list/Linked_list.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/game/board/linked_list/Linked_list.cpp.i
.PHONY : src/1model/game/board/linked_list/Linked_list.cpp.i

src/1model/game/board/linked_list/Linked_list.s: src/1model/game/board/linked_list/Linked_list.cpp.s

.PHONY : src/1model/game/board/linked_list/Linked_list.s

# target to generate assembly for a file
src/1model/game/board/linked_list/Linked_list.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/game/board/linked_list/Linked_list.cpp.s
.PHONY : src/1model/game/board/linked_list/Linked_list.cpp.s

src/1model/game/board/linked_list/node/Node.o: src/1model/game/board/linked_list/node/Node.cpp.o

.PHONY : src/1model/game/board/linked_list/node/Node.o

# target to build an object file
src/1model/game/board/linked_list/node/Node.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/game/board/linked_list/node/Node.cpp.o
.PHONY : src/1model/game/board/linked_list/node/Node.cpp.o

src/1model/game/board/linked_list/node/Node.i: src/1model/game/board/linked_list/node/Node.cpp.i

.PHONY : src/1model/game/board/linked_list/node/Node.i

# target to preprocess a source file
src/1model/game/board/linked_list/node/Node.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/game/board/linked_list/node/Node.cpp.i
.PHONY : src/1model/game/board/linked_list/node/Node.cpp.i

src/1model/game/board/linked_list/node/Node.s: src/1model/game/board/linked_list/node/Node.cpp.s

.PHONY : src/1model/game/board/linked_list/node/Node.s

# target to generate assembly for a file
src/1model/game/board/linked_list/node/Node.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/game/board/linked_list/node/Node.cpp.s
.PHONY : src/1model/game/board/linked_list/node/Node.cpp.s

src/1model/game/game.o: src/1model/game/game.cpp.o

.PHONY : src/1model/game/game.o

# target to build an object file
src/1model/game/game.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/game/game.cpp.o
.PHONY : src/1model/game/game.cpp.o

src/1model/game/game.i: src/1model/game/game.cpp.i

.PHONY : src/1model/game/game.i

# target to preprocess a source file
src/1model/game/game.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/game/game.cpp.i
.PHONY : src/1model/game/game.cpp.i

src/1model/game/game.s: src/1model/game/game.cpp.s

.PHONY : src/1model/game/game.s

# target to generate assembly for a file
src/1model/game/game.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/1model/game/game.cpp.s
.PHONY : src/1model/game/game.cpp.s

src/2view/GUI/Bounce.o: src/2view/GUI/Bounce.cpp.o

.PHONY : src/2view/GUI/Bounce.o

# target to build an object file
src/2view/GUI/Bounce.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/Bounce.cpp.o
.PHONY : src/2view/GUI/Bounce.cpp.o

src/2view/GUI/Bounce.i: src/2view/GUI/Bounce.cpp.i

.PHONY : src/2view/GUI/Bounce.i

# target to preprocess a source file
src/2view/GUI/Bounce.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/Bounce.cpp.i
.PHONY : src/2view/GUI/Bounce.cpp.i

src/2view/GUI/Bounce.s: src/2view/GUI/Bounce.cpp.s

.PHONY : src/2view/GUI/Bounce.s

# target to generate assembly for a file
src/2view/GUI/Bounce.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/Bounce.cpp.s
.PHONY : src/2view/GUI/Bounce.cpp.s

src/2view/GUI/ClickableCell.o: src/2view/GUI/ClickableCell.cpp.o

.PHONY : src/2view/GUI/ClickableCell.o

# target to build an object file
src/2view/GUI/ClickableCell.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/ClickableCell.cpp.o
.PHONY : src/2view/GUI/ClickableCell.cpp.o

src/2view/GUI/ClickableCell.i: src/2view/GUI/ClickableCell.cpp.i

.PHONY : src/2view/GUI/ClickableCell.i

# target to preprocess a source file
src/2view/GUI/ClickableCell.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/ClickableCell.cpp.i
.PHONY : src/2view/GUI/ClickableCell.cpp.i

src/2view/GUI/ClickableCell.s: src/2view/GUI/ClickableCell.cpp.s

.PHONY : src/2view/GUI/ClickableCell.s

# target to generate assembly for a file
src/2view/GUI/ClickableCell.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/ClickableCell.cpp.s
.PHONY : src/2view/GUI/ClickableCell.cpp.s

src/2view/GUI/GameWindow.o: src/2view/GUI/GameWindow.cpp.o

.PHONY : src/2view/GUI/GameWindow.o

# target to build an object file
src/2view/GUI/GameWindow.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/GameWindow.cpp.o
.PHONY : src/2view/GUI/GameWindow.cpp.o

src/2view/GUI/GameWindow.i: src/2view/GUI/GameWindow.cpp.i

.PHONY : src/2view/GUI/GameWindow.i

# target to preprocess a source file
src/2view/GUI/GameWindow.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/GameWindow.cpp.i
.PHONY : src/2view/GUI/GameWindow.cpp.i

src/2view/GUI/GameWindow.s: src/2view/GUI/GameWindow.cpp.s

.PHONY : src/2view/GUI/GameWindow.s

# target to generate assembly for a file
src/2view/GUI/GameWindow.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/GameWindow.cpp.s
.PHONY : src/2view/GUI/GameWindow.cpp.s

src/2view/GUI/MenuWindow.o: src/2view/GUI/MenuWindow.cpp.o

.PHONY : src/2view/GUI/MenuWindow.o

# target to build an object file
src/2view/GUI/MenuWindow.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/MenuWindow.cpp.o
.PHONY : src/2view/GUI/MenuWindow.cpp.o

src/2view/GUI/MenuWindow.i: src/2view/GUI/MenuWindow.cpp.i

.PHONY : src/2view/GUI/MenuWindow.i

# target to preprocess a source file
src/2view/GUI/MenuWindow.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/MenuWindow.cpp.i
.PHONY : src/2view/GUI/MenuWindow.cpp.i

src/2view/GUI/MenuWindow.s: src/2view/GUI/MenuWindow.cpp.s

.PHONY : src/2view/GUI/MenuWindow.s

# target to generate assembly for a file
src/2view/GUI/MenuWindow.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/MenuWindow.cpp.s
.PHONY : src/2view/GUI/MenuWindow.cpp.s

src/2view/GUI/Rectangle.o: src/2view/GUI/Rectangle.cpp.o

.PHONY : src/2view/GUI/Rectangle.o

# target to build an object file
src/2view/GUI/Rectangle.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/Rectangle.cpp.o
.PHONY : src/2view/GUI/Rectangle.cpp.o

src/2view/GUI/Rectangle.i: src/2view/GUI/Rectangle.cpp.i

.PHONY : src/2view/GUI/Rectangle.i

# target to preprocess a source file
src/2view/GUI/Rectangle.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/Rectangle.cpp.i
.PHONY : src/2view/GUI/Rectangle.cpp.i

src/2view/GUI/Rectangle.s: src/2view/GUI/Rectangle.cpp.s

.PHONY : src/2view/GUI/Rectangle.s

# target to generate assembly for a file
src/2view/GUI/Rectangle.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/Rectangle.cpp.s
.PHONY : src/2view/GUI/Rectangle.cpp.s

src/2view/GUI/WelcomeWindow.o: src/2view/GUI/WelcomeWindow.cpp.o

.PHONY : src/2view/GUI/WelcomeWindow.o

# target to build an object file
src/2view/GUI/WelcomeWindow.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/WelcomeWindow.cpp.o
.PHONY : src/2view/GUI/WelcomeWindow.cpp.o

src/2view/GUI/WelcomeWindow.i: src/2view/GUI/WelcomeWindow.cpp.i

.PHONY : src/2view/GUI/WelcomeWindow.i

# target to preprocess a source file
src/2view/GUI/WelcomeWindow.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/WelcomeWindow.cpp.i
.PHONY : src/2view/GUI/WelcomeWindow.cpp.i

src/2view/GUI/WelcomeWindow.s: src/2view/GUI/WelcomeWindow.cpp.s

.PHONY : src/2view/GUI/WelcomeWindow.s

# target to generate assembly for a file
src/2view/GUI/WelcomeWindow.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/WelcomeWindow.cpp.s
.PHONY : src/2view/GUI/WelcomeWindow.cpp.s

src/2view/GUI/animation.o: src/2view/GUI/animation.cpp.o

.PHONY : src/2view/GUI/animation.o

# target to build an object file
src/2view/GUI/animation.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/animation.cpp.o
.PHONY : src/2view/GUI/animation.cpp.o

src/2view/GUI/animation.i: src/2view/GUI/animation.cpp.i

.PHONY : src/2view/GUI/animation.i

# target to preprocess a source file
src/2view/GUI/animation.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/animation.cpp.i
.PHONY : src/2view/GUI/animation.cpp.i

src/2view/GUI/animation.s: src/2view/GUI/animation.cpp.s

.PHONY : src/2view/GUI/animation.s

# target to generate assembly for a file
src/2view/GUI/animation.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/animation.cpp.s
.PHONY : src/2view/GUI/animation.cpp.s

src/2view/GUI/canvas.o: src/2view/GUI/canvas.cpp.o

.PHONY : src/2view/GUI/canvas.o

# target to build an object file
src/2view/GUI/canvas.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/canvas.cpp.o
.PHONY : src/2view/GUI/canvas.cpp.o

src/2view/GUI/canvas.i: src/2view/GUI/canvas.cpp.i

.PHONY : src/2view/GUI/canvas.i

# target to preprocess a source file
src/2view/GUI/canvas.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/canvas.cpp.i
.PHONY : src/2view/GUI/canvas.cpp.i

src/2view/GUI/canvas.s: src/2view/GUI/canvas.cpp.s

.PHONY : src/2view/GUI/canvas.s

# target to generate assembly for a file
src/2view/GUI/canvas.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/canvas.cpp.s
.PHONY : src/2view/GUI/canvas.cpp.s

src/2view/GUI/sketchable.o: src/2view/GUI/sketchable.cpp.o

.PHONY : src/2view/GUI/sketchable.o

# target to build an object file
src/2view/GUI/sketchable.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/sketchable.cpp.o
.PHONY : src/2view/GUI/sketchable.cpp.o

src/2view/GUI/sketchable.i: src/2view/GUI/sketchable.cpp.i

.PHONY : src/2view/GUI/sketchable.i

# target to preprocess a source file
src/2view/GUI/sketchable.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/sketchable.cpp.i
.PHONY : src/2view/GUI/sketchable.cpp.i

src/2view/GUI/sketchable.s: src/2view/GUI/sketchable.cpp.s

.PHONY : src/2view/GUI/sketchable.s

# target to generate assembly for a file
src/2view/GUI/sketchable.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/2view/GUI/sketchable.cpp.s
.PHONY : src/2view/GUI/sketchable.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parameters.o: src/parameters.cpp.o

.PHONY : src/parameters.o

# target to build an object file
src/parameters.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/parameters.cpp.o
.PHONY : src/parameters.cpp.o

src/parameters.i: src/parameters.cpp.i

.PHONY : src/parameters.i

# target to preprocess a source file
src/parameters.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/parameters.cpp.i
.PHONY : src/parameters.cpp.i

src/parameters.s: src/parameters.cpp.s

.PHONY : src/parameters.s

# target to generate assembly for a file
src/parameters.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/parameters.cpp.s
.PHONY : src/parameters.cpp.s

src/test.o: src/test.cpp.o

.PHONY : src/test.o

# target to build an object file
src/test.cpp.o:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/test.cpp.o
.PHONY : src/test.cpp.o

src/test.i: src/test.cpp.i

.PHONY : src/test.i

# target to preprocess a source file
src/test.cpp.i:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/test.cpp.i
.PHONY : src/test.cpp.i

src/test.s: src/test.cpp.s

.PHONY : src/test.s

# target to generate assembly for a file
src/test.cpp.s:
	$(MAKE) -f CMakeFiles/KanaCrush.dir/build.make CMakeFiles/KanaCrush.dir/src/test.cpp.s
.PHONY : src/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... KanaCrush"
	@echo "... src/1model/Menu.o"
	@echo "... src/1model/Menu.i"
	@echo "... src/1model/Menu.s"
	@echo "... src/1model/Welcome.o"
	@echo "... src/1model/Welcome.i"
	@echo "... src/1model/Welcome.s"
	@echo "... src/1model/game/board/Mboard.o"
	@echo "... src/1model/game/board/Mboard.i"
	@echo "... src/1model/game/board/Mboard.s"
	@echo "... src/1model/game/board/cell/Mcell.o"
	@echo "... src/1model/game/board/cell/Mcell.i"
	@echo "... src/1model/game/board/cell/Mcell.s"
	@echo "... src/1model/game/board/linked_list/Linked_list.o"
	@echo "... src/1model/game/board/linked_list/Linked_list.i"
	@echo "... src/1model/game/board/linked_list/Linked_list.s"
	@echo "... src/1model/game/board/linked_list/node/Node.o"
	@echo "... src/1model/game/board/linked_list/node/Node.i"
	@echo "... src/1model/game/board/linked_list/node/Node.s"
	@echo "... src/1model/game/game.o"
	@echo "... src/1model/game/game.i"
	@echo "... src/1model/game/game.s"
	@echo "... src/2view/GUI/Bounce.o"
	@echo "... src/2view/GUI/Bounce.i"
	@echo "... src/2view/GUI/Bounce.s"
	@echo "... src/2view/GUI/ClickableCell.o"
	@echo "... src/2view/GUI/ClickableCell.i"
	@echo "... src/2view/GUI/ClickableCell.s"
	@echo "... src/2view/GUI/GameWindow.o"
	@echo "... src/2view/GUI/GameWindow.i"
	@echo "... src/2view/GUI/GameWindow.s"
	@echo "... src/2view/GUI/MenuWindow.o"
	@echo "... src/2view/GUI/MenuWindow.i"
	@echo "... src/2view/GUI/MenuWindow.s"
	@echo "... src/2view/GUI/Rectangle.o"
	@echo "... src/2view/GUI/Rectangle.i"
	@echo "... src/2view/GUI/Rectangle.s"
	@echo "... src/2view/GUI/WelcomeWindow.o"
	@echo "... src/2view/GUI/WelcomeWindow.i"
	@echo "... src/2view/GUI/WelcomeWindow.s"
	@echo "... src/2view/GUI/animation.o"
	@echo "... src/2view/GUI/animation.i"
	@echo "... src/2view/GUI/animation.s"
	@echo "... src/2view/GUI/canvas.o"
	@echo "... src/2view/GUI/canvas.i"
	@echo "... src/2view/GUI/canvas.s"
	@echo "... src/2view/GUI/sketchable.o"
	@echo "... src/2view/GUI/sketchable.i"
	@echo "... src/2view/GUI/sketchable.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parameters.o"
	@echo "... src/parameters.i"
	@echo "... src/parameters.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

